//declares the sonnets, speeches, and prologues that will be randomly selected, with lists combining the strings.

const sonnet2 = "When forty winters shall beseige thy brow\n And dig deep trenches in thy beauty's field\n Thy youth's proud livery, so gazed on now\n Will be a tatter'd weed, of small worth held\n Then being ask'd where all thy beauty lies\n Where all the treasure of thy lusty days\n To say, within thine own deep-sunken eyes\n Were an all-eating shame and thriftless praise\n How much more praise deserved thy beauty's use\n If thou couldst answer 'This fair child of min\n Shall sum my count and make my old excuse,\n Proving his beauty by succession thine\n This were to be new made when thou art old\n And see thy blood warm when thou feel'st it cold\n William Shakespeare Sonnet 2";
const sonnet119 = "What potions have I drunk of Siren tears\n Distill'd from limbecks foul as hell within\n Applying fears to hopes and hopes to fears\n Still losing when I saw myself to win\n What wretched errors hath my heart committed\n Whilst it hath thought itself so blessed never\n How have mine eyes out of their spheres been fitte\n In the distraction of this madding fever\n O benefit of ill! now I find tru\n That better is by evil still made better\n And ruin'd love, when it is built anew\n Grows fairer than at first, more strong, far greater\n So I return rebuked to my conten\n And gain by ill thrice more than I have spent\n William Shakespeare Sonnet 119";
const sonnet120 = "That you were once unkind befriends me now\n And for that sorrow which I then did fee\n Needs must I under my transgression bow\n Unless my nerves were brass or hammer'd steel\n For if you were by my unkindness shake\n As I by yours, you've pass'd a hell of time\n And I, a tyrant, have no leisure take\n To weigh how once I suffered in your crime\n O, that our night of woe might have remember'\n My deepest sense, how hard true sorrow hits\n And soon to you, as you to me, then tender'\n The humble slave which wounded bosoms fits\n But that your trespass now becomes a fee\n Mine ransoms yours, and yours must ransom me\n William Shakespeare Sonnet 120";
const sonnet94 = "They that have power to hurt and will do none\n That do not do the thing they most do show\n Who, moving others, are themselves as stone\n Unmoved, cold, and to temptation slow\n They rightly do inherit heaven's grace\n And husband nature's riches from expense\n They are the lords and owners of their faces\n Others but stewards of their excellence\n The summer's flower is to the summer sweet\n Though to itself it only live and die\n But if that flower with base infection meet\n The basest weed outbraves his dignity\n For sweetest things turn sourest by their deeds\n Lilies that fester smell far worse than weeds\n William Shakespeare Sonnet 94";
const sonnet121 = "'Tis better to be vile than vile esteem'd\n When not to be receives reproach of being\n And the just pleasure lost which is so deem'\n Not by our feeling but by others' seeing\n For why should others false adulterate eye\n Give salutation to my sportive blood\n Or on my frailties why are frailer spies\n Which in their wills count bad what I think good\n No, I am that I am, and they that leve\n At my abuses reckon up their own\n I may be straight, though they themselves be bevel\n By their rank thoughts my deeds must not be shown\n Unless this general evil they maintain\n All men are bad, and in their badness reign\n William Shakespeare Sonnet 121";
const sonnet49 = "Against that time, if ever that time come\n When I shall see thee frown on my defects\n When as thy love hath cast his utmost sum\n Call'd to that audit by advised respects\n Against that time when thou shalt strangely pas\n And scarcely greet me with that sun thine eye\n When love, converted from the thing it was\n Shall reasons find of settled gravity,-\n Against that time do I ensconce me her\n Within the knowledge of mine own desert\n And this my hand against myself uprear\n To guard the lawful reasons on thy part\n To leave poor me thou hast the strength of laws\n Since why to love I can allege no cause\n William Shakespeare Sonnet 49";
const sonnet140 = "Be wise as thou art cruel; do not pres\n My tongue-tied patience with too much disdain\n Lest sorrow lend me words and words expres\n The manner of my pity-wanting pain\n If I might teach thee wit, better it were\n Though not to love, yet, love, to tell me so\n As testy sick men, when their deaths be near\n No news but health from their physicians know\n For if I should despair, I should grow mad\n And in my madness might speak ill of thee\n Now this ill-wresting world is grown so bad\n Mad slanderers by mad ears believed be\n That I may not be so, nor thou belied\n Bear thine eyes straight, though thy proud heart go wide.";

const speech1 = "I do much wonder that one man, seeing how much another man is a fool when he dedicates his behaviors to love, will, after he hath laughed at such shallow follies in others, become the argument of his own scorn by failing in love: and such a man is Claudio. I have known when there was no music with him but the drum and the fife; and now had he rather hear the tabor and the pipe: I have known when he would have walked ten mile a-foot to see a good armor; and now will he lie ten nights awake, carving the fashion of a new doublet. He was wont to speak plain and to the purpose, like an honest man and a soldier; and now is he turned orthography; his words are a very fantastical banquet, just so many strange dishes. May I be so converted and see with these eyes? I cannot tell; I think not: I will not be sworn, but love may transofrm me to an oyster; but I'll take my oath on it, till he have made an oyster of me, he shall never make me such a fool. One woman is fair, yet I am well; another is wise, yet I am well; another virtuous, yet I am well; but till all graces be in one woman, one woman shall not come in my grace. Rich she shall be, that's certain; wise, or I'll none; virtuous, or I'll never cheapener her; fair, or I'll never look on her; mild, or come not near me; noble or not I for an angel; of good discourse, and excellent musician, and her hair shall be of what color it please God. Ha! the prince and Monsieur Love! I will hide me in the arbor. Benedick, Much Ado About Nothing";
const speech2 = "O, she misused me past the endurance of a block! an oak but with one green leaf on it would have answered her; my very visor began to assume life and scold with her. She told me, not thinking I had been myself, that I was the prince's jester, that I was duller than a great thaw; huddling jest upon jest with such impossible conveyance upon me that I stood like a man at a mark, with a whole army shooting at me. She speaks poniards, and every word stabs: if her breath were as terrible as her terminations, there were no living near her; she would infect to the north star. I would not marry her, though she were endowed with all that Adam bad left him before he transgressed: she would have made Hercules have turned spit, yea, and have cleft his club to make the fire too. Come, talk not of her: you shall find her the infernal Ate in good apparel. I would to God some scholar would conjure her; for certainly, while she is here, a man may live as quiet in hell as in a sanctuary; and people sin upon purpose, because they would go thither; so, indeed, all disquiet, horror and perturbation follows her. Benedick, Much Ado About Nothing";
const speech3 = "'Tis only title thou disdain'st in her, the which I can build up. Strange is it that our bloods, Of colour, weight, and heat, pour'd all together, Would quite confound distinction, yet stand off In differences so mighty. If she be All that is virtuous, save what thou dislikest, A poor physician's daughter, thou dislikest Of virtue for the name: but do not so: From lowest place when virtuous things proceed, The place is dignified by the doer's deed: Where great additions swell's, and virtue none, It is a dropsied honour. Good alone Is good without a name. Vileness is so: The property by what it is should go, Not by the title. She is young, wise, fair; In these to nature she's immediate heir, And these breed honour: that is honour's scorn, Which challenges itself as honour's born And is not like the sire: honours thrive, When rather from our acts we them derive Than our foregoers: the mere word's meaningless Debosh'd on every tomb, on every grave A lying trophy, and as oft is dumb Where dust and damn'd oblivion is the tomb Of honour'd bones indeed. What should be said? If thou canst like this creature as a maid, I can create the rest: virtue and she Is her own dower; honour and wealth from me. King of France, All's Well That Ends Well";
const speech4 = "All the world's a stage, And all the men and women merely players: They have their exits and their entrances; And one man in his time plays many parts, His acts being seven ages. At first the infant, Mewling and puking in the nurse's arms. And then the whining school-boy, with his satchel And shining morning face, creeping like snail Unwillingly to school. And then the lover, Sighing like furnace, with a woeful ballad Made to his mistress' eyebrow. Then a soldier, Full of strange oaths and bearded like the pard, Jealous in honour, sudden and quick in quarrel, Seeking the bubble reputation Even in the cannon's mouth. And then the justice, In fair round belly with good capon lined, With eyes severe and beard of formal cut, Full of wise saws and modern instances; And so he plays his part. The sixth age shifts Into the lean and slipper'd pantaloon, With spectacles on nose and pouch on side, His youthful hose, well saved, a world too wide For his shrunk shank; and his big manly voice, Turning again toward childish treble, pipes And whistles in his sound. Last scene of all, That ends this strange eventful history, Is second childishness and mere oblivion, Sans teeth, sans eyes, sans taste, sans everything. Jaques, As You Like It";
const speech5 = "Now I am alone. O, what a rogue and peasant slave am I! Is it not monstrous that this player here, But in a fiction, in a dream of passion, Could force his soul so to his own conceit That from her working all his visage wann'd, Tears in his eyes, distraction in's aspect, A broken voice, and his whole function suiting With forms to his conceit? and all for nothing! For Hecuba! What's Hecuba to him, or he to Hecuba, That he should weep for her? What would he do, Had he the motive and the cue for passion That I have? He would drown the stage with tears And cleave the general ear with horrid speech, Make mad the guilty and appal the free, Confound the ignorant, and amaze indeed The very faculties of eyes and ears. Yet I, A dull and muddy-mettled rascal, peak, Like John-a-dreams, unpregnant of my cause, And can say nothing; no, not for a king, Upon whose property and most dear life A damn'd defeat was made. Am I a coward? Who calls me villain? breaks my pate across? Plucks off my beard, and blows it in my face? Tweaks me by the nose? gives me the lie i' the throat, As deep as to the lungs? who does me this?... Hamlet, Hamlet";
const speech6 = "... If we are mark'd to die, we are enow To do our country loss; and if to live, The fewer men, the greater share of honour. God's will! I pray thee, wish not one man more. By Jove, I am not covetous for gold, Nor care I who doth feed upon my cost; It yearns me not if men my garments wear; Such outward things dwell not in my desires: But if it be a sin to covet honour, I am the most offending soul alive. No, faith, my coz, wish not a man from England: God's peace! I would not lose so great an honour As one man more, methinks, would share from me For the best hope I have. O, do not wish one more! Rather proclaim it, Westmoreland, through my host, That he which hath no stomach to this fight, Let him depart; his passport shall be made And crowns for convoy put into his purse: We would not die in that man's company That fears his fellowship to die with us. This day is called the feast of Crispian: He that outlives this day, and comes safe home, Will stand a tip-toe when the day is named, And rouse him at the name of Crispian. He that shall live this day, and see old age, Will yearly on the vigil feast his neighbours, And say 'To-morrow is Saint Crispian:' Then will he strip his sleeve and show his scars. And say 'These wounds I had on Crispin's day.' Old men forget: yet all shall be forgot, But he'll remember with advantages What feats he did that day: then shall our names. Familiar in his mouth as household words Harry the king, Bedford and Exeter, Warwick and Talbot, Salisbury and Gloucester, Be in their flowing cups freshly remember'd. This story shall the good man teach his son; And Crispin Crispian shall ne'er go by, From this day to the ending of the world, But we in it shall be remember'd; We few, we happy few, we band of brothers; For he to-day that sheds his blood with me Shall be my brother; be he ne'er so vile, This day shall gentle his condition: And gentlemen in England now a-bed Shall think themselves accursed they were not here, And hold their manhoods cheap whiles any speaks That fought with us upon Saint Crispin's day. King Henry V, Henry V" ;


const prologue1 = "O for a Muse of fire, that would ascend The brightest heaven of invention, A kingdom for a stage, princes to act And monarchs to behold the swelling scene! Then should the warlike Harry, like himself, Assume the port of Mars; and at his heels, Leash'd in like hounds, should famine, sword and fire Crouch for employment. But pardon, and gentles all, The flat unraised spirits that have dared On this unworthy scaffold to bring forth So great an object: can this cockpit hold The vasty fields of France? or may we cram Within this wooden O the very casques That did affright the air at Agincourt? O, pardon! since a crooked figure may Attest in little place a million; And let us, ciphers to this great accompt, On your imaginary forces work. Suppose within the girdle of these walls Are now confined two mighty monarchies, Whose high upreared and abutting fronts The perilous narrow ocean parts asunder: Piece out our imperfections with your thoughts; Into a thousand parts divide on man, And make imaginary puissance; Think when we talk of horses, that you see them Printing their proud hoofs i' the receiving earth; For 'tis your thoughts that now must deck our kings, Carry them here and there; jumping o'er times, Turning the accomplishment of many years Into an hour-glass: for the which supply, Admit me Chorus to this history; Who prologue-like your humble patience pray, Gently to hear, kindly to judge, our play. Henry V" ;
const prologue2 = "Two households, both alike in dignity, In fair Verona, where we lay our scene, From ancient grudge break to new mutiny, Where civil blood makes civil hands unclean. From forth the fatal loins of these two foes A pair of star-cross'd lovers take their life; Whose misadventured piteous overthrows Do with their death bury their parents' strife. The fearful passage of their death-mark'd love, And the continuance of their parents' rage, Which, but their children's end, nought could remove, Is now the two hours' traffic of our stage; The which if you with patient ears attend, What here shall miss, our toil shall strive to mend. Romeo And Juliet" ;
const prologue3 = "I come no more to make you laugh: things now, That bear a weighty and a serious brow, Sad, high, and working, full of state and woe, Such noble scenes as draw the eye to flow, We now present. Those that can pity, here May, if they think it well, let fall a tear; The subject will deserve it. Such as give Their money out of hope they may believe, May here find truth too. Those that come to see Only a show or two, and so agree The play may pass, if they be still and willing, I'll undertake may see away their shilling Richly in two short hours. Only they That come to hear a merry bawdy play, A noise of targets, or to see a fellow In a long motley coat guarded with yellow, Will be deceived; for, gentle hearers, know, To rank our chosen truth with such a show As fool and fight is, beside forfeiting Our own brains, and the opinion that we bring, To make that only true we now intend, Will leave us never an understanding friend. Therefore, for goodness' sake, and as you are known The first and happiest hearers of the town, Be sad, as we would make ye: think ye see The very persons of our noble story As they were living; think you see them great, And follow'd with the general throng and sweat Of thousand friends; then in a moment, see How soon this mightiness meets misery: And, if you can be merry then, I'll say A man may weep upon his wedding-day. Henry VIII" 
const prologue4 = "Now is the winter of our discontent Made glorious summer by this sun of York; And all the clouds that lour'd upon our house In the deep bosom of the ocean buried. Now are our brows bound with victorious wreaths; Our bruised arms hung up for monuments; Our stern alarums changed to merry meetings, Our dreadful marches to delightful measures. Grim-visaged war hath smooth'd his wrinkled front; And now, instead of mounting barbed steeds To fright the souls of fearful adversaries, He capers nimbly in a lady's chamber To the lascivious pleasing of a lute. But I, that am not shaped for sportive tricks, Nor made to court an amorous looking-glass; I, that am rudely stamp'd, and want love's majesty To strut before a wanton ambling nymph; I, that am curtail'd of this fair proportion, Cheated of feature by dissembling nature, Deformed, unfinish'd, sent before my time Into this breathing world, scarce half made up, And that so lamely and unfashionable That dogs bark at me as I halt by them; Why, I, in this weak piping time of peace, Have no delight to pass away the time, Unless to spy my shadow in the sun And descant on mine own deformity: And therefore, since I cannot prove a lover, To entertain these fair well-spoken days, I am determined to prove a villain And hate the idle pleasures of these days. Plots have I laid, inductions dangerous, By drunken prophecies, libels and dreams, To set my brother Clarence and the king In deadly hate the one against the other: And if King Edward be as true and just As I am subtle, false and treacherous, This day should Clarence closely be mew'd up, About a prophecy, which says that 'G' Of Edward's heirs the murderer shall be. Dive, thoughts, down to my soul: here Clarence comes." 


const sonnetList = [sonnet2, sonnet119, sonnet120, sonnet94, sonnet121, sonnet49, sonnet140 ];
const speechList = [speech1, speech2, speech3, speech4, speech5, speech6];
const prologueList = [prologue1, prologue2, prologue3, prologue4];

// choose a random sonnet
const sonnetPicker = () =>{
    let sonneti;
    let randomSonnet = "";
    sonneti = Math.floor(Math.random() * sonnetList.length -1);
    if(sonneti < 0){
        sonneti = 0;
    }
    randomSonnet = sonnetList[sonneti];
    return `A random sonnet: ${randomSonnet}`;
    
}

// choose a random speech
const speechPicker = () => {
    let speechi;
    let randomSpeech = "";
    speechi = Math.floor(Math.random()* speechList.length-1);
    if (speechi < 0){
        speechi = 0;
    }
    randomSpeech = speechList[speechi];
    return `A random speech: ${randomSpeech}`;

}

//choose a random prologue
const prologuePicker = () => {
    let proi;
    let randomPrologue = "";
    proi = Math.floor(Math.random() * prologueList.length -1);
    if (proi < 0){
        proi = 0;
    }
    randomPrologue = prologueList[proi];
    return `A random prologue: ${randomPrologue}`;
}
//puts everything together

console.log(`Your choosen selection:\n\n ${sonnetPicker()} \n\n ${speechPicker()} \n\n${prologuePicker()} \n\n to see a new selection click again!`)


//console.log(sonnetPicker());
//console.log(speechPicker());
//console.log(prologuePicker());