const sonnet1 = "FROM fairest creatures we desire increase,<br>That thereby beauty's rose might never die,<br>But as the riper should by time decease,<br>His tender heir might bear his memory:<br>But thou, contracted to thine own bright eyes,<br>Feed'st thy light'st flame with self-substantial fuel,<br>Making a famine where abundance lies,<br>Thyself thy foe, to thy sweet self too cruel.<br>Thou that art now the world's fresh ornament<br>And only herald to the gaudy spring,<br>Within thine own bud buriest thy content<br>And, tender churl, makest waste in niggarding.<br>Pity the world, or else this glutton be,<br>To eat the world's due, by the grave and thee.<br>William Shakespeare Sonnet 1" ;
const sonnet2 = "When forty winters shall beseige thy brow,<br>And dig deep trenches in thy beauty's field,<br>Thy youth's proud livery, so gazed on now,<br>Will be a tatter'd weed, of small worth held:<br>Then being ask'd where all thy beauty lies,<br>Where all the treasure of thy lusty days,<br>To say, within thine own deep-sunken eyes,<br>Were an all-eating shame and thriftless praise.<br>How much more praise deserved thy beauty's use,<br>If thou couldst answer 'This fair child of mine<br>Shall sum my count and make my old excuse,'<br>Proving his beauty by succession thine!<br>This were to be new made when thou art old,<br>And see thy blood warm when thou feel'st it cold.<br>William Shakespeare Sonnet 2";
const sonnet119 = "What potions have I drunk of Siren tears,<br>Distill'd from limbecks foul as hell within,<br>Applying fears to hopes and hopes to fears,<br>Still losing when I saw myself to win!<br>What wretched errors hath my heart committed,<br>Whilst it hath thought itself so blessed never!<br>How have mine eyes out of their spheres been fitted<br>In the distraction of this madding fever!<br>O benefit of ill! now I find true<br>That better is by evil still made better;<br>And ruin'd love, when it is built anew,<br>Grows fairer than at first, more strong, far greater.<br>So I return rebuked to my content<br>And gain by ill thrice more than I have spent.<br>William Shakespeare Sonnet 119";
const sonnet120 = "That you were once unkind befriends me now,<br>And for that sorrow which I then did feel<br>Needs must I under my transgression bow,<br>Unless my nerves were brass or hammer'd steel.<br>For if you were by my unkindness shaken<br>As I by yours, you've pass'd a hell of time,<br>And I, a tyrant, have no leisure taken<br>To weigh how once I suffered in your crime.<br>O, that our night of woe might have remember'd<br>My deepest sense, how hard true sorrow hits,<br>And soon to you, as you to me, then tender'd<br>The humble slave which wounded bosoms fits!<br>But that your trespass now becomes a fee;<br>Mine ransoms yours, and yours must ransom me.<br>William Shakespeare Sonnet 120";
const sonnet94 = "They that have power to hurt and will do none,<br>That do not do the thing they most do show,<br>Who, moving others, are themselves as stone,<br>Unmoved, cold, and to temptation slow,<br>They rightly do inherit heaven's graces<br>And husband nature's riches from expense;<br>They are the lords and owners of their faces,<br>Others but stewards of their excellence.<br>The summer's flower is to the summer sweet,<br>Though to itself it only live and die,<br>But if that flower with base infection meet,<br>The basest weed outbraves his dignity:<br>For sweetest things turn sourest by their deeds;<br>Lilies that fester smell far worse than weeds.<br>William Shakespeare Sonnet 94";
const sonnet121 = "'Tis better to be vile than vile esteem'd,<br>When not to be receives reproach of being,<br>And the just pleasure lost which is so deem'd<br>Not by our feeling but by others' seeing:<br>For why should others false adulterate eyes<br>Give salutation to my sportive blood?<br>Or on my frailties why are frailer spies,<br>Which in their wills count bad what I think good?<br>No, I am that I am, and they that level<br>At my abuses reckon up their own:<br>I may be straight, though they themselves be bevel;<br>By their rank thoughts my deeds must not be shown;<br>Unless this general evil they maintain,<br>All men are bad, and in their badness reign.<br>William Shakespeare Sonnet 121";
const sonnet49 = "Against that time, if ever that time come,<br>When I shall see thee frown on my defects,<br>When as thy love hath cast his utmost sum,<br>Call'd to that audit by advised respects;<br>Against that time when thou shalt strangely pass<br>And scarcely greet me with that sun thine eye,<br>When love, converted from the thing it was,<br>Shall reasons find of settled gravity,--<br>Against that time do I ensconce me here<br>Within the knowledge of mine own desert,<br>And this my hand against myself uprear,<br>To guard the lawful reasons on thy part:<br>To leave poor me thou hast the strength of laws,<br>Since why to love I can allege no cause.<br>William Shakespeare Sonnet 49";
const sonnet140 = "Be wise as thou art cruel; do not press<br>My tongue-tied patience with too much disdain;<br>Lest sorrow lend me words and words express<br>The manner of my pity-wanting pain.<br>If I might teach thee wit, better it were,<br>Though not to love, yet, love, to tell me so;<br>As testy sick men, when their deaths be near,<br>No news but health from their physicians know;<br>For if I should despair, I should grow mad,<br>And in my madness might speak ill of thee:<br>Now this ill-wresting world is grown so bad,<br>Mad slanderers by mad ears believed be,<br>That I may not be so, nor thou belied,<br>Bear thine eyes straight, though thy proud heart go wide.";



const sonnetList = [sonnet1, sonnet2, sonnet119, sonnet120, sonnet94, sonnet121, sonnet49, sonnet140 ];   
console.log(sonnetList);